function getMapSpriteDict()
{
	return mapSpriteDict;
}

var mapSpriteDict = {"Archer":"Archer", "Archer_F":"Archer_F", 
					 "ArcherinBallista":"ArcherinBallista", "ArcherinIronBallista":"ArcherinBallista", "ArcherinKillerBallista":"ArcherinBallista",
					 "Archsage":"Archsage",
					 "Assassin":"Assassin", "Assassin_F":"Assassin_F", "HungLeila":"Assasin_F",
					 "Bard":"Bard",
					 "Berserker":"Berserker", "Corsair":"Berserker",
					 "Bishop":"Bishop", "Bishop_F":"Bishop_F",
					 "BladeLord":"BladeLord",
					 "Blight":"Blight", "Entombed":"Blight",
					 "Brammimond":"Brammimond",
					 "Brigand":"Brigand",
					 "Cavalier":"Cavalier", "Cavalier_F":"Cavalier",
					 "Cleric":"Cleric",
					 "Civilian":"Civilian", "Civilian_2":"Civilian", "Civilian_F":"Civilian_F", "Civilian_2_F":"Civilian_F",
					 "Child":"Child", "Child_2":"Child", "Child_F":"Child_F", "Child_2_F":"Child_F",
					 "Dancer":"Dancer",
					 "DarkDruid":"DarkDruid",
					 "Druid":"Druid", "Druid_F":"Druid_F",
					 "EmptyBallista":"EmptyBallista", "EmptyIronBallista":"EmptyBallista", "EmptyKillerBallista":"EmptyBallista",
					 "FalcoKnight":"FalcoKnight",
					 "FallenIceDragon":"FallenIceDragon","FallenNinian":"FallenNinian",
					 "FallenPrince":"FallenPrince",
					 "FallenWarrior":"FallenWarrior",
					 "Fighter":"Fighter",
					 "FireDragon":"FireDragon",
					 "General":"General", "General_F":"General",
					 "GreatLord":"GreatLord",
					 "Hero":"Hero", "Hero_F":"Hero_F",
					 "Knight":"Knight", "Knight_F":"Knight",
					 "KnightLord":"KnightLord",
					 "EliwoodLord":"EliwoodLord",
					 "HectorLord":"HectorLord",
					 "LynLord":"LynLord",
					 "Mage":"Mage", "Mage_F":"Mage_F",
					 "MagicSeal":"MagicSeal",
					 "Mercenary":"Mercenary", "Mercenary_F":"Mercenary_F",
					 "Monk":"Monk",
					 "Myrmidon":"Myrmidon", "Myrmidon_F":"Myrmidon_F",
					 "Nomad":"Nomad", "Nomad_F":"Nomad_F",
					 "NomadTrooper":"NomadTrooper", "NomadTrooper_F":"NomadTrooper_F",
					 "Paladin":"Paladin", "Paladin_F":"Paladin",
					 "PegasusKnight":"PegasusKnight",
					 "Peer":"Peer", "Peer_F":"Peer_F",
					 "Pirate":"Pirate",
					 "Priest":"Priest",
					 "Prince":"Prince", "Princefacingupward":"Prince",
					 "Queen":"Queen",
					 "Sage":"Sage", "Sage_F":"Sage_F", "UberSage":"Sage",
					 "Shaman":"Shaman", "Shaman_F":"Shaman_F",
					 "Sniper":"Sniper", "Sniper_F":"Sniper_F",
					 "Soldier":"Soldier",
					 "Swordmaster":"Swordmaster", "Swordmaster_F":"Swordmaster_F",
					 "Prince_Tactician":"Tactician",
					 "Transporter":"Tent", "Tent":"Tent",
					 "Thief":"Thief", "Thief_F":"Thief_F",
					 "Troubadour":"Troubadour",
					 "TransporterHorse":"TransporterHorse",
					 "Valkyrie":"Valkyrie",
					 "Wagon":"TransporterHorse",
					 "Warrior":"Warrior",
					 "WyvernLord":"WyvernLord", "WyvernLord_F":"WyvernLord",
					 "WyvernKnight":"WyvernKnight", "WyvernKnight_F":"WyvernKnight",
					 "Zombie":"Zombie"
					 }