function getMapSpriteDict()
{
	return mapSpriteDict;
}

var mapSpriteDict = {"Archer":"Archer", "Archer_F":"Archer_F", 
					 "ArcheronBallista":"ArcherinBallista", "ArcheronIronBallista":"ArcherinBallista", "ArcheronKillerBallista":"ArcherinBallista",
					 "Archsage":"Archsage",
					 "Assassin":"Assassin", "Assassin_F":"Assassin_F",
					 "Bael":"Bael", "ElderBael":"ElderBael",
					 "Bard":"Bard",
					 "Berserker":"Berserker", "Corsair":"Berserker",
					 "Bishop":"Bishop", "Bishop_F":"Bishop_F",
					 "BladeLord":"BladeLord",
					 "Blight":"Blight",
					 "Bonewalker":"Bonewalker", "Bonewalker_Bow":"Bonewalker_Bow",
					 "Brammimond":"Brammimond",
					 "Brigand":"Brigand",
					 "Cavalier":"Cavalier", "Cavalier_F":"Cavalier",
					 "Cleric":"Cleric",
					 "Civilian":"Civilian", "Civilian_2":"Civilian", "Civilian_F":"Civilian_F", "Civilian_2_F":"Civilian_F", "Civilian_3":"Civilian",
					 "Child":"Child", "Child_2":"Child", "Child_F":"Child_F", "Child_2_F":"Child_F",
					 "Cyclops":"Cyclops",
					 "Dancer":"Dancer_T",
					 "DarkDruid":"DarkDruid",
					 "DemonKing":"DemonKing",
					 "DracoZombie":"DracoZombie",
					 "Druid":"Druid", "Druid_F":"Druid_F",
					 "EirikaLord":"EirikaLord", "EirikaMasterLord":"EirikaMasterLord", 
					 "EmptyBallista":"EmptyBallista", "EmptyIronBallista":"EmptyBallista", "EmptyKillerBallista":"EmptyBallista",
					 "Entombed":"Entombed",
					 "EphraimLord":"EphraimLord", "EphraimMasterLord":"EphraimMasterLord", 
					 "FalcoKnight":"FalcoKnight",
					 "FallenIceDragon":"FallenIceDragon","FallenNinian":"FallenNinian",
					 "FallenPrince":"FallenPrince",
					 "FallenWarrior":"FallenWarrior",
					 "Fighter":"Fighter",
					 "FireDragon":"FireDragon",
					 "Fleet":"Fleet",
					 "Gargoyle":"Gargoyle", "Deathgoyle":"Deathgoyle",
					 "General":"General", "General_F":"General",
					 "Gorgon":"Gorgon", "GorgonEgg":"GorgonEgg", "GorgonEgg_2":"GorgonEgg",
					 "GreatLord":"GreatLord", "GreatKnight":"GreatKnight", "GreatKnight_F":"GreatKnight", 
					 "Hero":"Hero", "Hero_F":"Hero_F",
					 "Journeyman_1":"Journeyman", "Journeyman_2":"Journeyman", "Journeyman_3":"Journeyman",
					 "Knight":"Knight", "Knight_F":"Knight",
					 "KnightLord":"KnightLord",
					 "EliwoodLord":"EliwoodLord",
					 "HectorLord":"HectorLord",
					 "LynLord":"LynLord",
					 "Mage":"Mage", "Mage_F":"Mage_F",
					 "MageKnight":"MageKnight", "MageKnight_F":"MageKnight_F",
					 "MagicSeal":"MagicSeal",
					 "Manakete_2":"Manakete_M", "Manakete_2_F":"Myrrh",
					 "Mauthedoog":"Mauthedoog", "Gwyllgi":"Gwyllgi", 
					 "Mercenary":"Mercenary", "Mercenary_F":"Mercenary_F",
					 "Mogall":"Mogall", "ArchMogall":"ArchMogall",
					 "Monk":"Monk",
					 "Myrmidon":"Myrmidon", "Myrmidon_F":"Myrmidon_F",
					 "Necromancer":"Necromancer",
					 "Nomad":"Nomad", "Nomad_F":"Nomad_F",
					 "NomadTrooper":"NomadTrooper", "NomadTrooper_F":"NomadTrooper_F",
					 "Paladin":"Paladin", "Paladin_F":"Paladin",
					 "PegasusKnight":"PegasusKnight",
					 "Peer":"Peer", "Peer_F":"Peer_F",
					 "Phantom":"Phantom", "GhostFighter":"Phantom",
					 "Pirate":"Pirate",
					 "Pontifex":"Pontifex",
					 "Priest":"Priest",
					 "Prince":"Prince", "Princefacingupward":"Prince", "Princess":"Princess",
					 "Pupil_1":"Pupil", "Pupil_2":"Pupil", "Pupil_3":"Pupil",
					 "Queen":"Queen",
					 "Ranger":"Ranger", "Ranger_F":"Ranger",
					 "Recruit_1":"Recruit", "Recruit_2":"Recruit", "Recruit_3":"Recruit", 
					 "Revenant":"Revenant",
					 "Rogue":"Rogue", 
					 "Sage":"Sage", "Sage_F":"Sage_F", "UberSage":"Sage",
					 "Shaman":"Shaman", "Shaman_F":"Shaman_F",
					 "Sniper":"Sniper", "Sniper_F":"Sniper_F",
					 "Soldier":"Soldier",
					 "Summoner":"Summoner", "Summoner_F":"Summoner",
					 "Swordmaster":"Swordmaster", "Swordmaster_F":"Swordmaster_F",
					 "Prince_Tactician":"Tactician",
					 "Tarvos":"Tarvos", "Maelduin":"Maelduin",
					 "Transporter":"Tent", "Tent":"Tent",
					 "Thief":"Thief", "Thief_F":"Thief_F",
					 "Troubadour":"Troubadour",
					 "TransporterHorse":"TransporterHorse",
					 "Valkyrie":"Valkyrie",
					 "Wagon":"TransporterHorse",
					 "Warrior":"Warrior",
					 "Wight":"Wight", "Wight_Bow":"Wight_Bow",
					 "WyvernLord":"WyvernLord", "WyvernLord_F":"WyvernLord",
					 "WyvernRider":"WyvernRider", "WyvernRider_F":"WyvernRider",
					 "WyvernKnight":"WyvernKnight", "WyvernKnight_F":"WyvernKnight",
					 "Zombie":"Zombie"
					 }