function getFE8Backgrounds()
{
	return FE8Backgrounds;
}

var FE8Backgrounds = ["House 0x00",
											"Saleh's House 0x01",
											"Village 0x02",
											"Outside of Village Day Time 0x03",
											"Outside of Village Evening 0x04",
											"Town Day Time 0x05",
											"Town (Past) 0x06",
											"Harbor 0x07",
											"Ship 0x08",
											"Inn 0x09",
											"Castle Hall 0x0A",
											"Castle Hall Night Time 0x0B",
											"Castle Hall 2 0x0C",
											"Castle Hall 2 (Past) 0x0D",
											"Castle Room 0x0E",
											"Castle Room (Past) 0x0F",
											"Castle Hall 3 0x10",
											"Castle Hall 3 Night Time 0x11",
											"Castle Hall 4 0x12",
											"Castle Garden 0x13",
											"Castle Garden (Past) 0x14",
											"Castle Outside 0x15",
											"Castle Outside (Past) 0x16",
											"Prison Cell 0x17",
											"Plain 0x18",
											"Plain Evening 0x19",
											"Plain Fog 0x1A",
											"Plain 2 0x1B",
											"Plain 3 0x1C",
											"Woodland 0x1D",
											"Woodland Fog 0x1E",
											"Woodland Evening 0x1F",
											"Woodland Night 0x20",
											"Riverside 0x21",
											"Forest 0x22",
											"Forest 2 0x23",
											"Town Gate 0x24",
											"Fort (Outside) 0x25",
											"Fort 0x26",
											"Fort Evening 0x27",
											"Fort (Ruins) 0x28",
											"Fort (Ruins) (Outside) 0x29",
											"Fort 2 0x2A",
											"Fort 2 Burning 0x2B",
											"Shrine 0x2C",
											"Shrine lighter 0x2D",
											"Shrine 2 0x2E",
											"Shrine 3 0x2F",
											"Desert 0x30",
											"Forest Dense 0x31",
											"Volcano 0x32",
											"Temple Gate 0x33",
											"Temple Ruins (Inside) 0x34",
											"Black (untested beyond this point) 0x35"];