function getFE7Music()
{
	return FE7Music;
}

var FE7Music = ["Nothing 0x00",
				"Precious Things 0x01",
				"Companions 0x02",
				"Friendship and Adventure 0x03",
				"Dragon's Gate II 0x04",
				"Scars of the Scouring 0x05",
				"Raise Your Spirits 0x06",
				"Shadow Approaches 0x07",
				"Binding Ties 0x08",
				"Winning Road 0x09",
				"Distant Travels 0x0A",
				"Inescapable Fate 0x0B",
				"Enemies Appear 0x0C",
				"The Messenger 0x0D",
				"Darkness Comes 0x0E",
				"Nabata's Wandering Messenger 0x0F",
				"Dragon's Gate I 0x10",
				"Legendary Inheritance 0x11",
				"Raid! 0x12",
				"Messenger from the Darkness 0x13",
				"Victory Now! 0x14",
				"Rise to the Challenge 0x15",
				"Softly with Grace 0x16",
				"Everything into the Dark 0x17",
				"Campaign of Fire 0x18",
				"Healing 0x19",
				"Curing 0x1A",
				"To the Heights 0x1B",
				"Blessing of the 8 Generals I 0x1C",
				"Receive the Blessings of Water 0x1D",
				"Ride the Wind 0x1E",
				"Strike 0x1F",
				"Safeguard 0x20",
				"Requiem 0x21",
				"Land of Swirling Sands 0x22",
				"The Kingdom of Bern 0x23",
				"Bern - A Mother's Wish 0x24",
				"A Hint of Things to Come 0x25",
				"Road of Trials 0x26",
				"Destiny Enlaced by Fear 0x27",
				"Nothing 0x28",
				"Results 0x29",
				"Treasured Hope 0x2A",
				"Game Over 0x2B",
				"Within Sadness 0x2C",
				"Arena Victory 0x2D",
				"Arena Tactics 0x2E",
				"Nothing 0x2F",
				"Winds Across the Plains 0x30",
				"Nothing 0x31",
				"An Unexpected Caller 0x32",
				"When the Rush Comes 0x33",
				"The Cogs of Fate 0x34",
				"Shocking Truth I 0x35",
				"Shocking Truth II 0x36",
				"The Eight Generals 0x37",
				"Triumph 0x38",
				"In the Shadow of Triumph 0x39",
				"Reminiscence 0x3A",
				"Nergal's Wrath 0x3B",
				"The Archsage Athos 0x3C",
				"One Heart: Eliwood's Theme 0x3D",
				"Loyalty: Hector's Theme 0x3E",
				"Girl of the Plains: Lyn's Theme 0x3F",
				"Final Farewell 0x40",
				"Going My Way 0x41",
				"Together, We Ride! 0x42",
				"A Knight's Oath 0x43",
				"Happiness Abounds 0x44",
				"Main Theme Arrangement 0x45",
				"Shop 0x46",
				"Arena Entrance 0x47",
				"Arena Battle 0x48",
				"Prepare to Charge 0x49",
				"Calamity Bringer: Nergal's Theme 0x4A",
				"Light to Tomorrow 0x4B",
				"Merchant Merlinus 0x4C",
				"Armory 0x4D",
				"Ships and Homes 0x4E",
				"Silent Ground 0x4F",
				"Black Fang 0x50",
				"Recollection of a Petal 0x51",
				"What Comes from Darkness 0x52",
				"Stratagem 0x53",
				"Lyn's Desire 0x54",
				"Nothing 0x55",
				"Eyes of Sorrow 0x56",
				"Unshakable Faith 0x57",
				"The Grieving Heart 0x58",
				"Nothing 0x59",
				"Fire Emblem Theme 0x5A",
				"Fire Emblem Theme (looped) 0x5B",
				"Opening: History Unveiled 0x5C",
				"Distant Utopia 0x5D",
				"Fortune Telling 0x5E",
				"Fire Emblem Theme (with intro) 0x5F",
				"Chapter Display humming 0x60",
				"Chapter Display 0x61",
				"Water Droplet in the Opening 0x62",
				"Sword Sound in the Opening 0x63",
				"What Comes from Darkness 0x64",
				"Black Fang 0x65",
				"Going My Way 0x66",
				"Safeguard 0x67",
				"Shattered Life 0x68",
				"Anguish 0x69",
				"Respite in Battle 0x6A",
				"The Inn 0x6B",
				"Nothing 0x6C",
				"Nothing 0x6D",
				"Blessing of the 8 Generals II 0x6E",
				"Campaign of Fire (no intro) 0x6F",
				"Beneath a New Light 0x70",
				"The Path to Greatness 0x71",
				"In the Name of Bern 0x72",
				"Legend of Athos 0x73",
				"Avoided Fate 0x74",
				"Legend of the God Dragon 0x75",
				"Royal Palace of Silezha 0x76",
				"??? 0x77",
				"??? (sounds like FE6's theme?) 0x78",
				"Ominius 0x79",
				"Fateful Showdown 0x7A",
				"Reign of Despair 0x7B",
				"Nothing 0x7C",
				"Nothing 0x7D",
				"Nothing 0x7E",
				"Nothing 0x7F",
				"Droplet? sounds familiar 0x80",
				"Crowd cheering 0x81",
				"Rest staff (map) 0x82",
				"Silence staff (map) 0x83",
				"Nothing 0x84",
				"Sleep staff (map) 0x85",
				"Hammerne staff (map) 0x86",
				"Berserk staff (map) 0x87",
				"Weird sound (Watch staff?) 0x88",
				"Live staff 0x89",
				"Relive staff 0x8A",
				"Recover staff 0x8B",
				"Reserve staff 0x8C",
				"Recovery from a status effect (longer) 0x8D",
				"Crowd cheering (softer) 0x8E",
				"Crowd cheering, then stops 0x8F",
				"FE6 Chapter opening humming 0x90",
				"FE6 Chapter opening 0x91",
				"Nothing 0x92",
				"Footsteps 0x93",
				"Footsteps 2 0x94",
				"Footsteps 3 0x95",
				"Footsteps 4 0x96",
				"Footsteps 5 0x97",
				"Footsteps 6 0x98",
				"Footsteps 7 0x99",
				"Footsteps 8 0x9A",
				"Horse trot 0x9B",
				"Horse trot 2 0x9C",
				"Horse trot 3 0x9D",
				"Horse trot 4 0x9E",
				"Horse trot 5 0x9F",
				"Armour walk 0xA0",
				"Armour walk 2 0xA1",
				"Armour walk 3 0xA2",
				"Armour walk 4 0xA3",
				"Armour walk 5 0xA4",
				"Armour walk 6 0xA5",
				"Pegasus flying 0xA6",
				"Pegasus flying 2 0xA7",
				"Nothing 0xA8",
				"Nothing 0xA9",
				"Recovery from a status effect 0xAA",
				"Rock exploding? 0xAB",
				"Captive falling from dead holder 0xAC",
				"Nothing 0xAD",
				"Nothing 0xAE",
				"Destroyed wall/snag 0xAF",
				"Attacking wall/snag 0xB0",
				"Unlocking door 0xB1",
				"Nothing 0xB2",
				"Torch 0xB3",
				"Warping 0xB4",
				"Warp end 0xB5",
				"Pure Water 0xB6",
				"Poison sound 0xB7",
				"??? 0xB8",
				"Gold changing 0xB9",
				"Poison vent 0xBA",
				"Nothing 0xBB",
				"Nothing 0xBC",
				"Water tile going under 0xBD",
				"Water tile coming up 0xBE",
				"Fire tile 0xBF",
				"Nothing 0xC0",
				"Nothing 0xC1",
				"Nothing 0xC2",
				"Nothing 0xC3",
				"Nothing 0xC4",
				"Nothing 0xC5",
				"Nothing 0xC6",
				"winds? 0xC7",
				"Small plunk? 0xC8",
				"Light plunk? 0xC9",
				"Large plunk? 0xCA",
				"Eliwood critical sword swing 0xCB",
				"Tap? 0xCC",
				"Low plunk? 0xCD",
				"Sword unsheathing 0xCE",
				"Sword unsheathing 2 0xCF",
				"Ballista fire 0xD0",
				"Creaking 0xD1",
				"Hit (map) 0xD2",
				"Hit 2 (map) 0xD3",
				"Hit 3 (map) 0xD4",
				"Kill (map) 0xD5",
				"Death (map) 0xD6",
				"Miss (realtime) 0xD7",
				"Crumbling? 0xD8",
				"Nothing 0xD9",
				"Nothing 0xDA",
				"Nothing 0xDB",
				"Mamkute transform 0xDC",
				"Mamkute de-transform 0xDD",
				"Mamkute yowl 0xDE",
				"Mamkute roar 0xDF",
				"Nothing 0xE0",
				"Nothing 0xE1",
				"Armour triangle, allies striking 0xE2",
				"Idoun/Fire Dragon death roar 0xE3",
				"Nothing 0xE4",
				"Idoun/Fire Dragon death roar 0xE5",
				"Mamkute transform growl 0xE6",
				"Brigand battle cry 0xE7",
				"Nothing 0xE8",
				"Nothing 0xE9",
				"Axe falling 0xEA",
				"Axe rising 0xEB",
				"Nothing 0xEC",
				"Nothing 0xED",
				"Nothing 0xEE",
				"Dance/Play effect 0xEF",
				"Divine weapon shine 0xF0",
				"Fire charge 0xF1",
				"Fire shoot 0xF2",
				"Nothing 0xF3",
				"Thunderstorm static 0xF4",
				"Thunderstorm strike 0xF5",
				"Shaman charging 0xF6",
				"Weird rumbling 0xF7",
				"Weird rumbling 2 0xF8",
				"Berserk staff (realtime) 0xF9",
				"Silence staff charging (realtime) 0xFA",
				"Silence staff forming (realtime) 0xFB",
				"Nothing 0xFC",
				"Rest staff (realtime) 0xFD",
				"Purge flash 0xFE",
				"Purge flash 2 0xFF",
				"Purge charging 0x100",
				"Purge strike 0x101",
				"Aureola light explosion (short) 0x102",
				"Hammerne staff (realtime) 0x103",
				"Nothing 0x104",
				"Nothing 0x105",
				"Nothing 0x106",
				"Nothing 0x107",
				"Nothing 0x108",
				"Nothing 0x109",
				"Flux charging 0x10A",
				"Nothing 0x10B",
				"Nothing 0x10C",
				"Nothing 0x10D",
				"Live staff 0x10E",
				"Live staff 0x10F",
				"Relive staff 0x110",
				"Relive staff 0x111",
				"Recover staff 0x112",
				"Recover staff 0x113",
				"Reserve staff (realtime) 0x114",
				"Nothing 0x115",
				"Nothing 0x116",
				"Nothing 0x117",
				"Nothing 0x118",
				"Thunderstorm sparks 0x119",
				"Thunderstorm strike 0x11A",
				"Sleep charging (realtime) 0x11B",
				"Sleep activating (realtime) 0x11C",
				"Rumbling? 0x11D",
				"Some kind of wind 0x11E",
				"Weird charging sound 0x11F",
				"Lightning charging 0x120",
				"Lightning strike 0x121",
				"Fimbulvetr wind 0x122",
				"Fimbulvetr ice 0x123",
				"Nosferatu symbol 0x124",
				"Nosferatu drain 0x125",
				"Nosferatu heal 0x126",
				"Divine charging 0x127",
				"Divine falling 0x128",
				"Divine strike 0x129",
				"Divine strike 2 0x12A",
				"Aureola light bomb falling 0x12B",
				"Aureola light explosion 0x12C",
				"Nothing 0x12D",
				"Nothing 0x12E",
				"Nothing 0x12F",
				"Nothing 0x130",
				"Nothing 0x131",
				"Nothing 0x132",
				"Nothing 0x133",
				"Nothing 0x134",
				"Nothing 0x135",
				"Nothing 0x136",
				"Nothing 0x137",
				"Nothing 0x138",
				"Nothing 0x139",
				"Nothing 0x13A",
				"Nothing 0x13B",
				"Nothing 0x13C",
				"Nothing 0x13D",
				"Nothing 0x13E",
				"Nothing 0x13F",
				"Nothing 0x140",
				"Nothing 0x141",
				"Nothing 0x142",
				"Nothing 0x143",
				"Nothing 0x144",
				"Nothing 0x145",
				"Nothing 0x146",
				"Nothing 0x147",
				"Nothing 0x148",
				"Nothing 0x149",
				"Nothing 0x14A",
				"Nothing 0x14B",
				"Nothing 0x14C",
				"Nothing 0x14D",
				"Soft step 0x14E",
				"Soft step 2 0x14F",
				"Soft step 3 0x150",
				"Soft step 4 0x151",
				"Nothing 0x152",
				"Nothing 0x153",
				"Soft step 0x154",
				"Soft step 2 0x155",
				"Soft step 3 0x156",
				"Soft step 4 0x157",
				"Soft step 5 0x158",
				"Soft step 6 0x159",
				"Nothing 0x2A0",
				"Nothing 0x2A8",
				"Nothing 0x2B0",
				"Nothing 0x2B1",
				"Nothing 0x2B2",
				"Nothing 0x2B5",
				"Nothing 0x2B6",
				"Nothing 0x2B9",
				"Nothing 0x2BB",
				"Shine attack 0x2BC",
				"Luna symbol 0x2BD",
				"Luna hitting 0x2BE",
				"Excalibur forming 0x2BF",
				"Excalibur cutting 0x2C0",
				"Aura flash 0x2C1",
				"Aura going up 0x2C2",
				"Aura strike 0x2C3",
				"Luce flash 0x2C4",
				"Luce charging 0x2C5",
				"Luce flowing 0x2C6",
				"Gespenst symbol 0x2C7",
				"Gespenst clouds 0x2C8",
				"Gespenst strike 0x2C9",
				"Forblaze charging 0x2CA",
				"Forblaze rising 0x2CB",
				"Weird charging 0x2CC",
				"Weird glittery sound 0x2CD",
				"No damage 0x2CE",
				"Weird pat sound 0x2CF",
				"Eliwood's sword shining 0x2D0",
				"Eliwood's horse neighing 0x2D1",
				"Weird flaming sound 0x2D2",
				"Dancing 0x2D3",
				"Playing 0x2D4",
				"Dancing (map) 0x2D5",
				"Playing (map) 0x2D6",
				"Snag falling 0x2D7",
				"Weird charging sound 0x2D8",
				"Thud 0x2D9",
				"Sword unsheathing 0x2DA",
				"Bizarre three sound effects 0x2DB",
				"A ref whistle? 0x2DC",
				"Glittery sound 0x2DD",
				"Shine sound 0x2DE",
				"Shine sound 2 0x2DF",
				"Weird rumbling 0x2E0",
				"Eclipse striking 0x2E1",
				"Eclipse striking (shorter) 0x2E2",
				"Dark Druid charging 0x2E3",
				"Nothing 0x2E4",
				"Nothing 0x2E5",
				"Nothing 0x2E6",
				"Nothing 0x2E7",
				"Dark Druid charging, then critical 0x2E8",
				"Magic shine 0x2E9",
				"Magic shine, long 0x2EA",
				"Magic shine, longer 0x2EB",
				"Magic shine, longer still 0x2EC",
				"Magic shine, longest 0x2ED",
				"Quintessence gathering 0x2EE",
				"Ninian ressurrection 0x2EF",
				"Rumbling at the Dragon's Gate 0x2F0",
				"Dragons screaming 0x2F1",
				"Fire Dragon dying 0x2F2",
				"Fire Dragon dying 2 0x2F3",
				"No damage 0x2F4",
				"High-pitched dragon yell 0x2F5",
				"Soft step 0x2F6",
				"Druid critical charge 0x2F7",
				"Sage critical conjuration 0x2F8",
				"Swish sound 0x2F9",
				"Icy sound 0x2FA",
				"Fire Dragon attacking 0x2FB",
				"Dragons attacking Athos 0x2FC",
				"Ereshkigal charging 0x2FD",
				"Ereshkigal strike 0x2FE",
				"Swoosh sound 0x2FF",
				"??? 0x300"];