function getFE7Backgrounds()
{
	return FE7Backgrounds;
}

var FE7Backgrounds = ["Lyn's Tent Background 0x00",
						"House with fireplace 0x01",
						"Village (Garden) 0x02",
						"Village (Garden) (Night) 0x03",
						"On a Road to a Town or Village 0x04",
						"On a Road to a Town or Village (Night) 0x05",
						"On a Road to a Town or Village (Sunset) 0x06",
						"On a Road to a Town or Village (Partial Dark) 0x07",
						"On a Road to a Town or Village (Lighter Thing?) 0x08",
						"Destroyed Village (Originally 0x02) 0x09",
						"Sea Port 0x0A",
						"Ship 0x0B",
						"Ocean Coast with Rocks 0x0C",
						"Hotel/House 0x0D",
						"Outside of Palace (One in Bern) 0x0E",
						"Outside of Castle (Special) 0x0F",
						"Inside of Castle (Bluish-Green Pillars) 0x10",
						"Same as 0x10, Darker 0x11",
						"Room in a Castle (Used in Laus and Caelin?) 0x12",
						"Same as 0x12, Darker 0x13",
						"Castle Room (Used in Bern) 0x14",
						"Castle Hall (Light-Colored Walls) 0x15",
						"Same as 0x15, Darker, Purple Walls 0x16",
						"Caelin Castle Garden (used in end of Lyn's Tale) 0x17",
						"Castle Garden with Bushes 0x18",
						"Castle Hallway, Door in Front 0x19",
						"Same as 0x19, Darker, Purple Walls 0x1A",
						"Prison/Cell 0x1B",
						"Outside, Forest on Left (Grass) 0x1C",
						"Plains with Hill and Mountains in background 0x1D",
						"Same as 0x1C, Sunset 0x1E",
						"Same as 0x1C, Dark/Night 0x1F",
						"Same as 0x1C, Foggy/Cloudy 0x20",
						"Same as 0x20, More Fog 0x21",
						"Plains 0x22",
						"Outside, Forest and Mountains Background 0x23",
						"Same as 0x23, Part Darker 0x24",
						"Same as 0x23, Fog 0x25",
						"Same as 0x23, Sunset 0x26",
						"Same as 0x24, Darker/Night 0x27",
						"Same as 0x24, Lighter 0x28",
						"Forest/Grass with Mountains (Special) 0x29",
						"Forest with Tall Trees 0x2A",
						"Forest (Special) 0x2B",
						"Forest (Different) 0x2C",
						"Forest with Light out of Corner 0x2D",
						"Forest of 0x2C (Foggy) 0x2E",
						"City (Bulgar) 0x2F",
						"City (Bulgar, Golden) 0x30",
						"Outside of City Gate 0x31",
						"Same as 0x31, Sunset 0x32",
						"Same as 0x31, Darker 0x33",
						"Same as 0x31 (???) 0x34",
						"House/Hotel with Bed 0x35",
						"Outside of Castle/Fortress (Brown) 0x36",
						"Outside of Castle/Fortress (Gray) 0x37",
						"Same as 0x36, Night 0x38",
						"Outside of Castle/Fortress (Different, Brown) 0x39",
						"Outside of Castle/Fortress (Different, Gray) 0x3A",
						"Same as 0x39, Different Palette 0x3B",
						"Castle/Dungeon (Inside) 0x3C",
						"Same as 0x3C, Night? (Purple) 0x3D",
						"Same as 0x3C, Sunset? 0x3E",
						"Outside, Abandoned Fortress Background 0x3F",
						"Same as 0x3F, Sunset 0x40",
						"Same as 0x3F, Foggy 0x41",
						"Inside Abandoned Fortress (Brown) 0x42",
						"Inside Abandoned Fortress (Purple/Dark?) 0x43",
						"Dragon's Gate Hall/Chamber (Brown) 0x44",
						"Dragon's Gate Hall/Chamber (Green) 0x45",
						"Dungeon Hallway (Brown) 0x46",
						"Dungeon Hallway (Blue) 0x47",
						"Dungeon Hallway (Green) 0x48",
						"Shrine/Alter 0x49",
						"Athos Shrine/Alter 0x4A",
						"Athos Shrine/Alter (Darker) 0x4B",
						"Shrine Hallway 0x4C",
						"Shrine Hallway (Darker) 0x4D",
						"Shrine Hallway (Purple) 0x4E",
						"Shrine/Alter 2 (Brown) 0x4F",
						"Shrine/Alter 2 (Golden) 0x50",
						"Desert 0x51",
						"Desert (Sunset) 0x52",
						"Dragon's Gate (Green) 0x53",
						"Dragon's Gate (Dark/Night) 0x54",
						"Fire Pit/Underworld 0x55",
						"Shrine/Alter 3 (Durandal?) 0x56",
						"Cave 0x57",
						"Shrine/Alter 4  0x58",
						"Sky 0x59",
						"Camp/Tent with Weapons 0x5A",
						"Black Background 0x5B",
						"Dragon's Gate (Close-Up) 0x5C",
						"Dragon's Gate (Close-Up) (Lighter) 0x5D",
						"To Be Continued 0x5E"];